<?php

namespace idoit\Module\Multiedit\Component\Multiedit\Formatter\Category\G\Contact;

use idoit\Module\Multiedit\Component\Multiedit\Formatter\Popup\ObjectBrowser;

class ContactObjectFormatter extends ObjectBrowser
{
    /**
     * @param \idoit\Module\Multiedit\Component\Multiedit\Formatter\ValueFormatter $valueFormatter
     *
     * @return string|void
     * @throws \Exception
     */
    public static function formatCell($valueFormatter)
    {
        parent::overwriteMultiSelection($valueFormatter);
        return parent::formatCell($valueFormatter); // TODO: Change the autogenerated stub
    }

    /**
     * @param \idoit\Module\Multiedit\Component\Multiedit\Formatter\ValueFormatter $valueFormatter
     *
     * @return \idoit\Module\Multiedit\Component\Multiedit\Formatter\Value
     */
    public static function formatSource($valueFormatter)
    {
        self::overwriteMultiSelection($valueFormatter);
        return parent::formatSource($valueFormatter); // TODO: Change the autogenerated stub
    }
}