idoit.Translate = new Hash({
    LC__CMDB__LOGBOOK__TITLE:                      '[{isys type="lang" ident="LC__CMDB__LOGBOOK__TITLE"}]',
    LC__CMDB__CATG__TYPE:                          '[{isys type="lang" ident="LC__CMDB__CATG__TYPE"}]',
    LC__CMDB__CATG__SYSID:                         '[{isys type="lang" ident="LC__CMDB__CATG__SYSID"}]',
    LC__CMDB__OBJECT_BROWSER__EXISTS_IN_SELECTION: '[{isys type="lang" ident="LC__CMDB__OBJECT_BROWSER__EXISTS_IN_SELECTION"}]',
    LC__CMDB__REMOVE_PROPERTY_CHAIN:               '[{isys type="lang" ident="LC__CMDB__REMOVE_PROPERTY_CHAIN"}]',
    // Translations for connection-browser.
    LC__CMDB__CATG__CONNECTORS:     '[{isys type="lang" ident="LC__CMDB__CATG__CONNECTORS"}]',
    LC__CMDB__CATG__UI_ASSIGNED_UI: '[{isys type="lang" ident="LC__CMDB__CATG__UI_ASSIGNED_UI"}]',
    LC__CMDB__CATG__CATEGORY:       '[{isys type="lang" ident="LC__CMDB__CATG__CATEGORY"}]',
    LC__CMDB__CATS__PRT_TYPE:       '[{isys type="lang" ident="LC__CMDB__CATS__PRT_TYPE"}]',
    // Translations for the notify-messages.
    LC__NOTIFY__MESSAGE: '[{isys type="lang" ident="LC__NOTIFY__MESSAGE"}]',
    LC__NOTIFY__SUCCESS: '[{isys type="lang" ident="LC__NOTIFY__SUCCESS"}]',
    LC__NOTIFY__ERROR:   '[{isys type="lang" ident="LC__NOTIFY__ERROR"}]',
    LC__NOTIFY__INFO:    '[{isys type="lang" ident="LC__NOTIFY__INFO"}]',
    LC__NOTIFY__WARNING: '[{isys type="lang" ident="LC__NOTIFY__WARNING"}]',
    // Translation for universal strings.
    LC_UNIVERSAL__ACCEPT:   '[{isys type="lang" ident="LC_UNIVERSAL__ACCEPT"}]',
    LC_UNIVERSAL__ABORT:    '[{isys type="lang" ident="LC_UNIVERSAL__ABORT"}]',
    LC__UNIVERSAL__LOADING: '[{isys type="lang" ident="LC__UNIVERSAL__LOADING"}]',
    LC__UNIVERSAL__YES:     '[{isys type="lang" ident="LC__UNIVERSAL__YES"}]',
    LC__UNIVERSAL__NO:      '[{isys type="lang" ident="LC__UNIVERSAL__NO"}]',
    LC__UNIVERSAL__SEARCH:  '[{isys type="lang" ident="LC__UNIVERSAL__SEARCH"}]',
    // Translation for object browser.
    LC__CMDB__OBJECT_BROWSER__SCRIPT_JS__EMPTY_RESULTS:   '[{isys type="lang" ident="LC__CMDB__OBJECT_BROWSER__SCRIPT_JS__EMPTY_RESULTS"}]',
    LC__CMDB__OBJECT_BROWSER__SCRIPT_JS__ERROR_DATA:      '[{isys type="lang" ident="LC__CMDB__OBJECT_BROWSER__SCRIPT_JS__ERROR_DATA"}]',
    LC__CMDB__OBJECT_BROWSER__SCRIPT_JS__ERROR_URL:       '[{isys type="lang" ident="LC__CMDB__OBJECT_BROWSER__SCRIPT_JS__ERROR_URL"}]',
    LC__CMDB__OBJECT_BROWSER__SCRIPT_JS__FILTER_LABEL:    '[{isys type="lang" ident="LC__CMDB__OBJECT_BROWSER__SCRIPT_JS__FILTER_LABEL"}]',
    LC__CMDB__OBJECT_BROWSER__SCRIPT_JS__LOADING:         '[{isys type="lang" ident="LC__CMDB__OBJECT_BROWSER__SCRIPT_JS__LOADING"}]',
    LC__CMDB__OBJECT_BROWSER__SCRIPT_JS__SEARCH_LABEL:    '[{isys type="lang" ident="LC__CMDB__OBJECT_BROWSER__SCRIPT_JS__SEARCH_LABEL"}]',
    LC__CMDB__OBJECT_BROWSER__SCRIPT_JS__PAGINATEN_OF:    '[{isys type="lang" ident="LC__CMDB__OBJECT_BROWSER__SCRIPT_JS__PAGINATEN_OF"}]',
    LC__CMDB__OBJECT_BROWSER__SCRIPT_JS__PAGINATEN_PAGES: '[{isys type="lang" ident="LC__CMDB__OBJECT_BROWSER__SCRIPT_JS__PAGINATEN_PAGES"}]',
    LC__UNIVERSAL__PAGER__FIRST_PAGE:                     '[{isys type="lang" ident="LC__UNIVERSAL__PAGER__FIRST_PAGE"}]',
    LC__UNIVERSAL__PAGER__PREVIOUS_PAGE:                  '[{isys type="lang" ident="LC__UNIVERSAL__PAGER__PREVIOUS_PAGE"}]',
    LC__UNIVERSAL__PAGER__NEXT_PAGE:                      '[{isys type="lang" ident="LC__UNIVERSAL__PAGER__NEXT_PAGE"}]',
    LC__UNIVERSAL__PAGER__LAST_PAGE:                      '[{isys type="lang" ident="LC__UNIVERSAL__PAGER__LAST_PAGE"}]',
    LC__CMDB__OBJECT_BROWSER__VALIDATION_EMPTY_N:         '[{isys type="lang" ident="LC__CMDB__OBJECT_BROWSER__VALIDATION_EMPTY_N"}]',
    // Translations for ajax uploads.
    LC_FILEBROWSER__DROP_FILE:          '[{isys type="lang" ident="LC_FILEBROWSER__DROP_FILE"}]',
    LC_FILEBROWSER__SINGLE_FILE_UPLOAD: '[{isys type="lang" ident="LC_FILEBROWSER__SINGLE_FILE_UPLOAD"}]',
    LC__UNIVERSAL__FILE_ADD:            '[{isys type="lang" ident="LC__UNIVERSAL__FILE_ADD"}]',
    LC__UNIVERSAL__ERROR:               '[{isys type="lang" ident="LC__UNIVERSAL__ERROR"}]',
    LC__UNIVERSAL__COLLAPSE:            '[{isys type="lang" ident="LC__UNIVERSAL__COLLAPSE"}]',
    LC__UNIVERSAL__EXPAND:              '[{isys type="lang" ident="LC__UNIVERSAL__EXPAND"}]'
});
